version: "3"
services:
  vue-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    environment:
      - VUE_APP_NAME=VueApp
      - CHOKIDAR_USEPOLLING=true